### ISSUE TITLE
SPIKE: How to add chart information to saved query data

### ISSUE THREAD

**Issue by rob-h-m** [SmartColumbusOS/discovery_ui#21]
@carriebrinkley commented on [Tue Aug 27 2019](https://github.com/smartcitiesdata/discovery_ui/issues/182)

### Business Value: 

This is a first slice of creating the ability for users to save/share queries for future use. The ultimate goal is to provide efficiencies for the end user so that coming to the platform will be a time-save for all of their data needs. 

### Acceptance Criteria: 

- [ ] When the user saves a visualization, the structure of the chart is saved as well
- [ ] When the user retrieves the visualization, the structure of the chart is retrieved and presented in the UI 
- [ ] Determine a path forward and write dev cards to make it real

#### Amigos

@jakeclark , @carriebrinkley , @LtChae

**Comment by cameronmarsh** [comment]
A plot can be represented in json with data, layout, and possibly frames. The chart editor can export / import these representation of the plot. Its is currently not doing that natively, and would have to be added by us. There are working examples of this using the react-chart-editor that we can base our work from. (see https://github.com/plotly/react-chart-editor/commit/e1e092dcc0c817afd66440dd2bee0bdd77b90cd9 with the `loadMock` function)

When saving a plot; the plot is not a template for the query, but a visualization of the data that was returned by that query at the time the chart was saved. IE: A saved query may return different data in the future, however since the data for the plot is saved w/ the plot, this new data would not be included when the plot is loaded.

Here are examples for plot.ly plots saved as JSON. https://github.com/plotly/plotly.js/tree/master/test/image/mocks

**Comment by cameronmarsh** [comment]
Saving and loading a visualization are separate issues, however, both can be derived from the same json data. 

Saving a visualization would include just getting the data and layout from the current state of the ChartEditor and saving them in the correct JSON format. (See https://plot.ly/javascript/reference/ for the hierarchical structure of possible JSON fields)

Loading a visualization will require setting the ChartEditor's plot component to use the data and layout specified in the JSON file. It will also require setting the state of the editor sidebar, whose settings can be derived from the data and layout (i.e. updating the traces and configs from the values in the JSON file). See the actions used in the `handleUpdate` function here : https://github.com/plotly/react-chart-editor/blob/10ec34f300aa322b9cd95dbbecf1b404ed2a7c9b/src/EditorControls.js (e.g. `EDITOR_ACTIONS.UPDATE_LAYOUT`)
