### ISSUE TITLE
Add "save as..." functionality to saving visualizations

### ISSUE THREAD

**Issue by cameronmarsh** [SmartColumbusOS/discovery_ui#66]
_As a user, I want to be able to save new copies of my named visualizations, so I can easily experiment with different ways of viewing the data._

#### Business Value
Currently when a user loads a saved visualization, modifies the SQL statement, and clicks the save button, the loaded visualization will be updated and overwritten (if the user has permission to do so). However, a user may want to modify a loaded visualization and save it without overwriting the original version. 

#### Acceptance Criteria
- [ ] The save icon has a dropdown arrow that presents the user with the option to save a new query 
- [ ] When the user clicks the save icon after loading a visualization, it is still updated (the user has to click the arrow to save a new query)
- [ ] The URL is updated when a new query is saved
- [ ] See attached UI design by @jakeclark 

#### Tech Notes
- A visualization has been loaded if there is an `id` in the URL (e.g. `/visualization/0u9qtwdj` instead of just `/visualization`)
- The backend functionality is already being built (https://github.com/SmartColumbusOS/discovery_ui/issues/12).  This is linking the front-end part.

#### UI

![IMG_0533](https://user-images.githubusercontent.com/13970182/67399950-f662dc00-f57a-11e9-9a86-ce7b45319f57.JPG)

**Comment by LtChae** [comment]
From a technical perspective, this may get a bit weird because users have no control over the underlying unique identifier. Example: user has a visualization called "Viz 1" and then creates "Viz 2" and saves as "Viz 1". What they'll end up with under their "My Visualizations" list is ["Viz 1", "Viz 1"] unless we do some magic behind the scenes. Definitely possible to work around, just worth keeping in my RE: complexity. - Ben
